// Mock data for local development without a database
// All shapes match Prisma query results exactly

const now = new Date().toISOString();

export const MOCK_CHARITIES = [
  {
    id: 'charity-001',
    name: 'Jordan Humanitarian Aid',
    nameAr: 'المساعدات الإنسانية الأردنية',
    description: 'Providing humanitarian aid across Jordan, focusing on food security, emergency relief, and community development programs for vulnerable families.',
    descriptionAr: 'تقديم المساعدات الإنسانية في جميع أنحاء الأردن',
    logoUrl: null,
    isVerified: true,
    contactEmail: 'info@jordanaid.org',
    contactPhone: null,
    website: null,
    isActive: true,
    createdAt: now,
    programs: [
      {
        id: 'prog-001',
        charityId: 'charity-001',
        title: 'Ramadan Food Basket Distribution',
        titleAr: 'توزيع سلال غذائية رمضانية',
        description: 'Help distribute food baskets to 500 families across Zarqa and East Amman during the holy month of Ramadan.',
        descriptionAr: null,
        location: 'Zarqa & East Amman',
        district: 'zarqa',
        maxVolunteers: 50,
        currentVolunteers: 23,
        startDate: '2026-03-10T00:00:00.000Z',
        endDate: '2026-04-08T00:00:00.000Z',
        status: 'open',
        createdAt: now,
      },
      {
        id: 'prog-002',
        charityId: 'charity-001',
        title: 'Winter Clothing Drive Volunteers',
        titleAr: 'متطوعون لحملة الملابس الشتوية',
        description: 'Collect, sort, and distribute winter clothing to families in need across northern Jordan.',
        descriptionAr: null,
        location: 'Irbid',
        district: 'irbid',
        maxVolunteers: 30,
        currentVolunteers: 12,
        startDate: '2026-03-15T00:00:00.000Z',
        endDate: null,
        status: 'open',
        createdAt: now,
      },
    ],
    donations: [],
    _count: { donations: 47, programs: 2 },
  },
  {
    id: 'charity-002',
    name: 'Tkiyet Um Ali',
    nameAr: 'تكية أم علي',
    description: 'The first and largest food aid organization in Jordan, serving underprivileged families with daily meals and long-term food security programs.',
    descriptionAr: 'أكبر مؤسسة للمساعدات الغذائية في الأردن',
    logoUrl: null,
    isVerified: true,
    contactEmail: 'info@tua.jo',
    contactPhone: null,
    website: 'https://www.tua.jo',
    isActive: true,
    createdAt: now,
    programs: [
      {
        id: 'prog-003',
        charityId: 'charity-002',
        title: 'Daily Iftar Meal Preparation',
        titleAr: 'تحضير وجبات إفطار يومية',
        description: 'Join our kitchen team to prepare and serve daily Iftar meals for 200+ people at our central kitchen.',
        descriptionAr: null,
        location: 'Amman Central Kitchen',
        district: 'jabal_amman',
        maxVolunteers: 20,
        currentVolunteers: 18,
        startDate: '2026-03-01T00:00:00.000Z',
        endDate: '2026-03-30T00:00:00.000Z',
        status: 'open',
        createdAt: now,
      },
    ],
    donations: [],
    _count: { donations: 132, programs: 1 },
  },
  {
    id: 'charity-003',
    name: 'Jordan Hashemite Charity Organization',
    nameAr: 'الهيئة الخيرية الأردنية الهاشمية',
    description: 'Leading charity providing relief and development programs in health, education, and emergency response across the Kingdom.',
    descriptionAr: 'مؤسسة خيرية رائدة في الإغاثة والتنمية',
    logoUrl: null,
    isVerified: true,
    contactEmail: null,
    contactPhone: null,
    website: null,
    isActive: true,
    createdAt: now,
    programs: [
      {
        id: 'prog-004',
        charityId: 'charity-003',
        title: 'Educational Tutoring for Refugee Children',
        titleAr: 'دروس تعليمية لأطفال اللاجئين',
        description: 'Provide after-school tutoring in Math, English, and Arabic for refugee children in Zaatari camp.',
        descriptionAr: null,
        location: 'Zaatari Camp',
        district: null,
        maxVolunteers: 15,
        currentVolunteers: 7,
        startDate: null,
        endDate: null,
        status: 'open',
        createdAt: now,
      },
    ],
    donations: [],
    _count: { donations: 89, programs: 1 },
  },
];

export const MOCK_LEADERBOARD = [
  { id: 'li-1', userId: 'user-001', userName: 'Ahmad Khalil', avatarUrl: null, impactScore: 847, tasksCompleted: 42, totalDonated: 350, createdAt: now, updatedAt: now },
  { id: 'li-2', userId: 'user-002', userName: 'Sara Nasser', avatarUrl: null, impactScore: 720, tasksCompleted: 35, totalDonated: 200, createdAt: now, updatedAt: now },
  { id: 'li-3', userId: 'user-003', userName: 'Omar Rizeq', avatarUrl: null, impactScore: 685, tasksCompleted: 31, totalDonated: 150, createdAt: now, updatedAt: now },
  { id: 'li-4', userId: 'user-004', userName: 'Layla Hassan', avatarUrl: null, impactScore: 590, tasksCompleted: 28, totalDonated: 180, createdAt: now, updatedAt: now },
  { id: 'li-5', userId: 'user-005', userName: 'Mohammad Ali', avatarUrl: null, impactScore: 520, tasksCompleted: 24, totalDonated: 120, createdAt: now, updatedAt: now },
  { id: 'li-6', userId: 'user-006', userName: 'Noor Amin', avatarUrl: null, impactScore: 480, tasksCompleted: 22, totalDonated: 90, createdAt: now, updatedAt: now },
  { id: 'li-7', userId: 'user-007', userName: 'Khaled Sami', avatarUrl: null, impactScore: 410, tasksCompleted: 18, totalDonated: 250, createdAt: now, updatedAt: now },
  { id: 'li-8', userId: 'user-008', userName: 'Rania Yousef', avatarUrl: null, impactScore: 380, tasksCompleted: 16, totalDonated: 80, createdAt: now, updatedAt: now },
  { id: 'li-9', userId: 'user-009', userName: 'Tariq Mahmoud', avatarUrl: null, impactScore: 350, tasksCompleted: 15, totalDonated: 60, createdAt: now, updatedAt: now },
  { id: 'li-10', userId: 'user-010', userName: 'Dina Faris', avatarUrl: null, impactScore: 290, tasksCompleted: 12, totalDonated: 100, createdAt: now, updatedAt: now },
  { id: 'li-11', userId: 'demo-user-001', userName: 'Demo User', avatarUrl: null, impactScore: 45, tasksCompleted: 2, totalDonated: 25, createdAt: now, updatedAt: now },
];

export const MOCK_DONATIONS = [
  {
    id: 'don-001',
    donorId: 'demo-user-001',
    donorName: 'Demo User',
    charityId: 'charity-002',
    amount: 25,
    currency: 'JOD',
    receiptNumber: 'TKF-M1X9A2-K7PQ',
    txHash: '0x8a2f3e7b1c9d4f6a0e5b2c8d1f3a7e9b4c6d0f2a5e8b1c3d7f9a2e4b6c8d0f',
    explorerUrl: 'https://sepolia.etherscan.io/tx/0x8a2f3e7b1c9d4f6a0e5b2c8d1f3a7e9b4c6d0f2a5e8b1c3d7f9a2e4b6c8d0f',
    status: 'confirmed',
    createdAt: '2026-03-01T14:30:00.000Z',
    charity: { id: 'charity-002', name: 'Tkiyet Um Ali', isVerified: true },
  },
];

export function getMockCharity(id: string) {
  return MOCK_CHARITIES.find((c) => c.id === id) || null;
}
